CREATE TABLE TECHNICIAN(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    EMAIL TEXT NOT NULL
);

CREATE TABLE COMPANY(
    TIN BIGINT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    ZIP_CODE TEXT NOT NULL,
    CITY TEXT NOT NULL,
    STREET TEXT NOT NULL
);

CREATE TABLE CUSTOMER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    PHONE_NUMBER TEXT,
    EMAIL TEXT,
    TIN BIGINT REFERENCES COMPANY(TIN),
    ID_ADDRESSES BIGINT ARRAY NOT NULL
);